u = env["res.users"].browse(85)
hu = env.ref("hr_holidays.group_hr_holidays_user")
hr = env.ref("hr_holidays.group_hr_holidays_responsible")
print("direct user", hu in u.group_ids)
print("direct resp", hr in u.group_ids)
print("all groups", u.group_ids.mapped("name"))
target = u._lug_target_group_ids()
print("target", [env["res.groups"].browse(i).name for i in target])
managed = env["res.users"]._lug_managed_group_ids()
print("holidays_user managed", hu.id in managed)
